/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinic;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.EventQueue;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;

/**
 *
 * @author PC
 */
public class FirstRunSetup extends javax.swing.JFrame {
     private static final int MAX_HEAD_ADMINS = 10;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FirstRunSetup.class.getName());

    /**
     * Creates new form FirstRunSetup
     */
    public FirstRunSetup() {
        initComponents(); 
    applyFlatLafStyles();
    setLocationRelativeTo(null);
    try {
        setIconImage(AppIcon.getIcon());
    } catch (Exception e) {
        // Fallback
    }
    }
    private void applyFlatLafStyles() {
    // Window Base Style
    getRootPane().putClientProperty("FlatLaf.style", "font: 14 $defaultFont.family");

    // ==========================================
    // 1. STYLE: Number Input Panel (jPanel2)
    // ==========================================
    NumberTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    NumberTxt.putClientProperty("JTextField.placeholderText", "e.g., 1");
    NumberTxt.putClientProperty("JTextField.arc", 12);
    NumberTxt.putClientProperty("JTextField.outline", "#CBD5E1");
    NumberTxt.putClientProperty("JTextField.padding", new java.awt.Insets(6, 10, 6, 10));

    NextButton.putClientProperty("JButton.buttonType", "roundRect");
    NextButton.putClientProperty("JButton.arc", 12);

    // ==========================================
    // 2. STYLE: Create Panel (jPanel3 Controls)
    // ==========================================
    
    // Header & Badge Styling
    jLabel7.putClientProperty("FlatLaf.style", "font: bold 22 $defaultFont.family; foreground: #0F172A;");
    NumberPlaceHolder.putClientProperty("FlatLaf.style", "font: bold 22 $defaultFont.family; foreground: #0284C7;");

    // Form Field Labels
    AccountNameLabel.putClientProperty("FlatLaf.style", "font: bold 13 $defaultFont.family; foreground: #475569;");
    AccountPasswordLabel.putClientProperty("FlatLaf.style", "font: bold 13 $defaultFont.family; foreground: #475569;");
    ConfirmPasswordLabel.putClientProperty("FlatLaf.style", "font: bold 13 $defaultFont.family; foreground: #475569;");

    // Text & Password Input Fields
    AccNameField.putClientProperty("JTextField.placeholderText", "Enter admin username...");
    AccNameField.putClientProperty("JTextField.arc", 12);
    AccNameField.putClientProperty("JTextField.outline", "#CBD5E1");
    AccNameField.putClientProperty("JTextField.padding", new java.awt.Insets(6, 10, 6, 10));

    AccPasswordField.putClientProperty("JTextField.placeholderText", "Enter password...");
    AccPasswordField.putClientProperty("JTextField.arc", 12);
    AccPasswordField.putClientProperty("JTextField.outline", "#CBD5E1");
    AccPasswordField.putClientProperty("JTextField.padding", new java.awt.Insets(6, 10, 6, 10));
    AccPasswordField.putClientProperty("JPasswordField.showRevealButton", true); // Optional eye button to toggle visibility

    ConfirmPasswordField1.putClientProperty("JTextField.placeholderText", "Re-enter password...");
    ConfirmPasswordField1.putClientProperty("JTextField.arc", 12);
    ConfirmPasswordField1.putClientProperty("JTextField.outline", "#CBD5E1");
    ConfirmPasswordField1.putClientProperty("JTextField.padding", new java.awt.Insets(6, 10, 6, 10));
    ConfirmPasswordField1.putClientProperty("JPasswordField.showRevealButton", true);

    // Buttons (NextButton1 = Next / Intermediate, NextButton2 = Final Confirm)
    NextButton1.putClientProperty("JButton.buttonType", "roundRect");
    NextButton1.putClientProperty("JButton.arc", 12);

    NextButton2.putClientProperty("JButton.buttonType", "roundRect");
    NextButton2.putClientProperty("JButton.arc", 12);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreatePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        NumberPlaceHolder = new javax.swing.JLabel();
        AccNameField = new javax.swing.JTextField();
        AccountNameLabel = new javax.swing.JLabel();
        AccountPasswordLabel = new javax.swing.JLabel();
        AccPasswordField = new javax.swing.JPasswordField();
        ConfirmPasswordLabel = new javax.swing.JLabel();
        ConfirmPasswordField1 = new javax.swing.JPasswordField();
        NextButton1 = new javax.swing.JButton();
        NextButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NumberTxt = new javax.swing.JTextField();
        NextButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CreatePanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Create Head Admin");

        NumberPlaceHolder.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        NumberPlaceHolder.setForeground(new java.awt.Color(0, 0, 0));

        AccNameField.addActionListener(this::AccNameFieldActionPerformed);

        AccountNameLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 13)); // NOI18N
        AccountNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        AccountNameLabel.setText("Account Name:");

        AccountPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 13)); // NOI18N
        AccountPasswordLabel.setForeground(new java.awt.Color(0, 0, 0));
        AccountPasswordLabel.setText("Account Password:");

        AccPasswordField.addActionListener(this::AccPasswordFieldActionPerformed);

        ConfirmPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 13)); // NOI18N
        ConfirmPasswordLabel.setForeground(new java.awt.Color(0, 0, 0));
        ConfirmPasswordLabel.setText("Confirm Password:");

        NextButton1.setBackground(new java.awt.Color(0, 102, 204));
        NextButton1.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        NextButton1.setForeground(new java.awt.Color(255, 255, 255));
        NextButton1.setText("Confirm");
        NextButton1.addActionListener(this::NextButton1ActionPerformed);

        NextButton2.setBackground(new java.awt.Color(0, 102, 204));
        NextButton2.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        NextButton2.setForeground(new java.awt.Color(255, 255, 255));
        NextButton2.setText("Next");
        NextButton2.addActionListener(this::NextButton2ActionPerformed);

        javax.swing.GroupLayout CreatePanelLayout = new javax.swing.GroupLayout(CreatePanel);
        CreatePanel.setLayout(CreatePanelLayout);
        CreatePanelLayout.setHorizontalGroup(
            CreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreatePanelLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NumberPlaceHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreatePanelLayout.createSequentialGroup()
                        .addGap(0, 174, Short.MAX_VALUE)
                        .addGroup(CreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreatePanelLayout.createSequentialGroup()
                                .addComponent(NextButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreatePanelLayout.createSequentialGroup()
                                .addGroup(CreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CreatePanelLayout.createSequentialGroup()
                                        .addGroup(CreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ConfirmPasswordLabel)
                                            .addComponent(AccountPasswordLabel)
                                            .addComponent(AccountNameLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(CreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AccNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ConfirmPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AccPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreatePanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(NextButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(82, 82, 82)))
                                .addGap(171, 171, 171))))))
        );
        CreatePanelLayout.setVerticalGroup(
            CreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(NumberPlaceHolder, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addGroup(CreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccountNameLabel))
                .addGap(18, 18, 18)
                .addGroup(CreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccountPasswordLabel))
                .addGap(18, 18, 18)
                .addGroup(CreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmPasswordLabel)
                    .addComponent(ConfirmPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(NextButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181)
                .addComponent(NextButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(CreatePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 0, 710, 710));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(15, 23, 42));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Create Head Admin");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 65, 85));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("How many Head admin accounts would you like to create?");

        NumberTxt.setBackground(new java.awt.Color(255, 255, 255));
        NumberTxt.setColumns(12);
        NumberTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NumberTxt.addActionListener(this::NumberTxtActionPerformed);

        NextButton.setBackground(new java.awt.Color(0, 102, 204));
        NextButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        NextButton.setForeground(new java.awt.Color(255, 255, 255));
        NextButton.setText("Continue");
        NextButton.putClientProperty("JButton.buttonType", "roundRect");
        NextButton.putClientProperty("FlatLaf.style", "font: 14 $font.family bold; background: #0066CC; foreground: #ffffff; arc: 12;");
        NextButton.addActionListener(this::NextButtonActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(NumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(283, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(24, 24, 24)
                .addComponent(NumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(247, 247, 247))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 0, 710, -1));

        jPanel1.setBackground(new java.awt.Color(15, 23, 42));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/logo2.png"))); // NOI18N

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Check in and inventory monitoring System ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(681, 681, 681))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(316, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 596, 712));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumberTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberTxtActionPerformed
         NextButtonActionPerformed(evt);
    }//GEN-LAST:event_NumberTxtActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
          String text =
                NumberTxt.getText() == null
                ? "" : NumberTxt.getText().trim();

        if (!text.matches("\\d+")) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please enter a whole number.",
                    "Invalid Number",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        int count;

        try {
            count = Integer.parseInt(text);
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please enter a valid number.",
                    "Invalid Number",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (count <= 0) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Number of Head Admins must be at least 1.",
                    "Invalid Number",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (count > MAX_HEAD_ADMINS) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Number of Head Admins cannot exceed "
                    + MAX_HEAD_ADMINS + ".",
                    "Invalid Number",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        dispose();
        new HeadAdminMakerUi(count).setVisible(true);
    }//GEN-LAST:event_NextButtonActionPerformed

    private void AccNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccNameFieldActionPerformed
       
    }//GEN-LAST:event_AccNameFieldActionPerformed

    private void AccPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccPasswordFieldActionPerformed
       
    }//GEN-LAST:event_AccPasswordFieldActionPerformed

    private void NextButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButton1ActionPerformed
        // "Next" — only visible on non-final Head Admins.
       
    }//GEN-LAST:event_NextButton1ActionPerformed

    private void NextButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButton2ActionPerformed
        // "Confirm" — only visible on the final Head Admin.
        
    }//GEN-LAST:event_NextButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            FlatLightLaf.setup();
        } catch (Exception ex) {
            logger.log(Level.SEVERE, "Failed to initialize FlatLaf", ex);
        }

        /* Create and display the form */
        EventQueue.invokeLater(() -> new FirstRunSetup().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccNameField;
    private javax.swing.JPasswordField AccPasswordField;
    private javax.swing.JLabel AccountNameLabel;
    private javax.swing.JLabel AccountPasswordLabel;
    private javax.swing.JPasswordField ConfirmPasswordField1;
    private javax.swing.JLabel ConfirmPasswordLabel;
    private javax.swing.JPanel CreatePanel;
    private javax.swing.JButton NextButton;
    private javax.swing.JButton NextButton1;
    private javax.swing.JButton NextButton2;
    private javax.swing.JLabel NumberPlaceHolder;
    private javax.swing.JTextField NumberTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
