/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinic;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.EventQueue;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;

/**
 *
 * @author PC
 */
public class FirstRunSetup extends javax.swing.JFrame {
     private static final int MAX_HEAD_ADMINS = 10;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FirstRunSetup.class.getName());

    /**
     * Creates new form FirstRunSetup
     */
    public FirstRunSetup() {
        initComponents(); 
    applyFlatLafStyles();
    setLocationRelativeTo(null);
    try {
        setIconImage(AppIcon.getIcon());
    } catch (Exception e) {
        // Fallback
    }
    }
    private void applyFlatLafStyles() {
    

    
getRootPane().putClientProperty("FlatLaf.style", "font: 14");

    NumberTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    NumberTxt.putClientProperty("JTextField.placeholderText", "e.g., 1");
    NumberTxt.putClientProperty("JTextField.arc", 12);
    NumberTxt.putClientProperty("JTextField.outline", "#CBD5E1");
    NumberTxt.putClientProperty("JTextField.padding", new java.awt.Insets(6, 10, 6, 10));


    NextButton.putClientProperty("JButton.buttonType", "roundRect");
    NextButton.putClientProperty("JButton.arc", 12);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NumberTxt = new javax.swing.JTextField();
        NextButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(15, 23, 42));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Create Head Admin");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 65, 85));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("How many Head admin accounts would you like to create?");

        NumberTxt.setBackground(new java.awt.Color(255, 255, 255));
        NumberTxt.setColumns(12);
        NumberTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NumberTxt.addActionListener(this::NumberTxtActionPerformed);

        NextButton.setBackground(new java.awt.Color(0, 102, 204));
        NextButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        NextButton.setForeground(new java.awt.Color(255, 255, 255));
        NextButton.setText("Continue");
        NextButton.putClientProperty("JButton.buttonType", "roundRect");
        NextButton.putClientProperty("FlatLaf.style", "font: 14 $font.family bold; background: #0066CC; foreground: #ffffff; arc: 12;");
        NextButton.addActionListener(this::NextButtonActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(NumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(283, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(24, 24, 24)
                .addComponent(NumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(247, 247, 247))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 0, 710, -1));

        jPanel1.setBackground(new java.awt.Color(15, 23, 42));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/logo2.png"))); // NOI18N

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Check in and inventory monitoring System ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(681, 681, 681))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(316, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 596, 712));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumberTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberTxtActionPerformed
         NextButtonActionPerformed(evt);
    }//GEN-LAST:event_NumberTxtActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
          String text =
                NumberTxt.getText() == null
                ? "" : NumberTxt.getText().trim();

        if (!text.matches("\\d+")) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please enter a whole number.",
                    "Invalid Number",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        int count;

        try {
            count = Integer.parseInt(text);
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please enter a valid number.",
                    "Invalid Number",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (count <= 0) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Number of Head Admins must be at least 1.",
                    "Invalid Number",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (count > MAX_HEAD_ADMINS) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Number of Head Admins cannot exceed "
                    + MAX_HEAD_ADMINS + ".",
                    "Invalid Number",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        dispose();
        new HeadAdminMakerUi(count).setVisible(true);
    }//GEN-LAST:event_NextButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            FlatLightLaf.setup();
        } catch (Exception ex) {
            logger.log(Level.SEVERE, "Failed to initialize FlatLaf", ex);
        }

        /* Create and display the form */
        EventQueue.invokeLater(() -> new FirstRunSetup().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NextButton;
    private javax.swing.JTextField NumberTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
