/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinic;

/**
 *
 * @author PC
 */
public class HeadAdminMakerUi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HeadAdminMakerUi.class.getName());

    private int totalHeadAdmins;
    private int currentIndex;
    private final java.util.List<AccountData.PendingHeadAdmin> pendingHeadAdmins = new java.util.ArrayList<>();
    private final AccountData accountData = new AccountData();

    /**
     * Only used by the NetBeans Form Editor for design-time preview.
     * Real usage goes through HeadAdminMakerUi(int).
     */
    public HeadAdminMakerUi() {
        this(1);
    }

    /**
     * @param totalHeadAdmins how many Head Admin accounts this wizard
     *                        instance will collect before creating them.
     */
    public HeadAdminMakerUi(int totalHeadAdmins) {
        this.totalHeadAdmins = totalHeadAdmins;
        this.currentIndex = 1;
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(AppIcon.getIcon());
        showStep();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AccNameField = new javax.swing.JTextField();
        AccPasswordField = new javax.swing.JPasswordField();
        ConfirmPasswordField1 = new javax.swing.JPasswordField();
        AccountNameLabel = new javax.swing.JLabel();
        AccountPasswordLabel = new javax.swing.JLabel();
        ConfirmPasswordLabel = new javax.swing.JLabel();
        NextButton = new javax.swing.JButton();
        NextButton1 = new javax.swing.JButton();
        NumberPlaceHolder = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/logo2.png"))); // NOI18N

        AccNameField.addActionListener(this::AccNameFieldActionPerformed);

        AccPasswordField.addActionListener(this::AccPasswordFieldActionPerformed);

        AccountNameLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 13)); // NOI18N
        AccountNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        AccountNameLabel.setText("Account Name:");

        AccountPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 13)); // NOI18N
        AccountPasswordLabel.setForeground(new java.awt.Color(0, 0, 0));
        AccountPasswordLabel.setText("Account Password:");

        ConfirmPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 13)); // NOI18N
        ConfirmPasswordLabel.setForeground(new java.awt.Color(0, 0, 0));
        ConfirmPasswordLabel.setText("Confirm Password:");

        NextButton.setBackground(new java.awt.Color(0, 102, 204));
        NextButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        NextButton.setForeground(new java.awt.Color(255, 255, 255));
        NextButton.setText("Confirm");
        NextButton.addActionListener(this::NextButtonActionPerformed);

        NextButton1.setBackground(new java.awt.Color(0, 102, 204));
        NextButton1.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        NextButton1.setForeground(new java.awt.Color(255, 255, 255));
        NextButton1.setText("Next");
        NextButton1.addActionListener(this::NextButton1ActionPerformed);

        NumberPlaceHolder.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        NumberPlaceHolder.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Create Head Admin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(836, Short.MAX_VALUE)
                        .addComponent(NumberPlaceHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AccountNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(AccountPasswordLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ConfirmPasswordLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AccNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(AccPasswordField)
                                        .addComponent(ConfirmPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NextButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(128, 128, 128))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(216, 216, 216)
                    .addComponent(jLabel4)
                    .addContainerGap(268, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(NumberPlaceHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(121, 121, 121)
                        .addComponent(NextButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AccNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AccountNameLabel))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AccPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AccountPasswordLabel))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ConfirmPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConfirmPasswordLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(290, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(jLabel4)
                    .addContainerGap(455, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccNameFieldActionPerformed
           handleStepSubmit();
    }//GEN-LAST:event_AccNameFieldActionPerformed

    private void AccPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccPasswordFieldActionPerformed
          handleStepSubmit();
    }//GEN-LAST:event_AccPasswordFieldActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
            // "Next" — only visible on non-final Head Admins.
        handleStepSubmit();
    }//GEN-LAST:event_NextButtonActionPerformed

    private void NextButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButton1ActionPerformed
          // "Confirm" — only visible on the final Head Admin.
        handleStepSubmit();
    }//GEN-LAST:event_NextButton1ActionPerformed

     private void showStep() {

        NumberPlaceHolder.setText(currentIndex + "/" + totalHeadAdmins);

        AccNameField.setText("");
        AccPasswordField.setText("");
        ConfirmPasswordField1.setText("");

        boolean isFinalStep = currentIndex == totalHeadAdmins;

        NextButton.setVisible(isFinalStep);
        NextButton1.setVisible(!isFinalStep);

        AccNameField.requestFocusInWindow();
    }

      private void handleStepSubmit() {

        String name =
                AccNameField.getText() == null
                ? "" : AccNameField.getText().trim();

        char[] password = AccPasswordField.getPassword();
        char[] confirm = ConfirmPasswordField1.getPassword();

        try {

            String error = validateHeadAdminStep(name, password, confirm);

            if (error != null) {
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        error,
                        "Invalid Entry",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            String passwordHash = PasswordHasher.hashPassword(password);

            pendingHeadAdmins.add(
                    new AccountData.PendingHeadAdmin(name, passwordHash));

            if (currentIndex == totalHeadAdmins) {
                finishSetup();
            } else {
                currentIndex++;
                showStep();
            }

        } finally {
            java.util.Arrays.fill(password, '\0');
            java.util.Arrays.fill(confirm, '\0');
        }
    }

    private String validateHeadAdminStep(
            String name, char[] password, char[] confirm) {

        if (name.isEmpty()) {
            return "Username is required.";
        }

        if (name.length() > 255) {
            return "Username must be 255 characters or fewer.";
        }

        if (password.length == 0) {
            return "Password is required.";
        }

        if (confirm.length == 0) {
            return "Please confirm the password.";
        }

        if (!java.util.Arrays.equals(password, confirm)) {
            return "Passwords do not match.";
        }

        for (AccountData.PendingHeadAdmin pending : pendingHeadAdmins) {
            if (pending.name().equalsIgnoreCase(name)) {
                return "That username is already used for "
                        + "another Head Admin in this setup.";
            }
        }

        try {
            if (accountData.nameExists(name)) {
                return "That username already exists.";
            }
        } catch (java.sql.SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE,
                    "Failed to check existing accounts.", ex);
            return "Could not verify the username right now. "
                    + "Please try again.";
        }

        return null;
    }

    private void finishSetup() {

        try {
            accountData.createInitialHeadAdmins(pendingHeadAdmins);

        } catch (java.sql.SQLException | SecurityException ex) {

            logger.log(java.util.logging.Level.SEVERE,
                    "Failed to create Head Admin accounts.", ex);

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Could not create the Head Admin accounts: "
                    + ex.getMessage(),
                    "Setup Failed",
                    javax.swing.JOptionPane.ERROR_MESSAGE);

            return;

        } finally {
            pendingHeadAdmins.clear();
        }

        dispose();
        new LoginUi().setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HeadAdminMakerUi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccNameField;
    private javax.swing.JPasswordField AccPasswordField;
    private javax.swing.JLabel AccountNameLabel;
    private javax.swing.JLabel AccountPasswordLabel;
    private javax.swing.JPasswordField ConfirmPasswordField1;
    private javax.swing.JLabel ConfirmPasswordLabel;
    private javax.swing.JButton NextButton;
    private javax.swing.JButton NextButton1;
    private javax.swing.JLabel NumberPlaceHolder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
